### PR TITLE
Add WP Rocket Delay JS exclusion for gpt.js

### PR DESCRIPTION
**Pull request by ecotechie**

### CODE REVIEW

**Comment by halounsbury** [comment]
Need it for Perfmatters too.

The issue with asking Mediavine to add this is that it's not actually their script. They just said that it is ad-related, and if it's not delayed, it can cause issues. 

I'd love to be able to tell our MV clients we took care of this for them.

**Comment by ecotechie** [comment]
This is ready for @blogtutor to merge and release.

**Comment by ecotechie** [comment]
Previous conversation on different repo:
https://github.com/blogtutor/np-dashboard/issues/410

**Comment by blogtutor** [comment]
@halounsbury is this really urgent enough for a new release?  That's a lot of work for our updates team to go through and update all (yet again).

Just want to be sure this is significant/urgent enough.

**Comment by halounsbury** [comment]
Apparently it is the script Raptive uses while gathering traffic info for a site prior to a site moving to them. And it can conflict with Mediavine ads displaying properly. I think having it tracking properly and ads displaying properly is a priority for a clients. We have lots of them switching to Raptive right now.

**Comment by blogtutor** [comment]
Ok.

@ecotechie note the above that this exclusion needs to be added to the perfmatters list, too.

**Comment by ecotechie** [comment]
Done

**Comment by blogtutor** [comment]
perfmatters doesn't use the backslash - that's why we needed a separate list

**Comment by ecotechie** [comment]
Aaaand removed the escape char for Perfmatters...

**Comment by ecotechie** [comment]
Should these be the same, except for the back slashes?
image

**Comment by blogtutor** [comment]
> Should these be the same, except for the back slashes?

Not exactly. @halounsbury had us adjust some for Rocket separately from Perfmatters.  So it's good we're keeping two lists.

**Comment by ecotechie** [comment]
Sounds good. Then it should be ready.

If we wanted the lists to be the same... We could just have an if statement triggered by a method's argument. This could strip the back slashes depending on need.

**Comment by halounsbury** [comment]
They should **not** be the same list. Some of the scripts have to be excluded from WP Rocket and not Perfmatters.

**Comment by blogtutor** [comment]
ok. testing now.

**Comment by blogtutor** [comment]
tested on dev.nerdpress.net.  exclusions work correctly for both rocket & perfmatters, tested against a list of all possible matches...

**Comment by blogtutor** [comment]
even this if this is a "hotfix" I am still going to follow the same process and merge into `dev` first.   this will keep everything consistent.  still gotta deal with bumping version, releases, etc.

**Comment by ecotechie** [comment]
@blogtutor If you merge into dev, then you are releasing things we may not intend to. A hotfix gets merged to the current main branch.

**Comment by ecotechie** [comment]
Unless, of course, you merge into dev to have the changes there. Then merge this hotfix into main and release.

**Comment by blogtutor** [comment]
@ecotechie Fair point... However, I don't ever want us to merge anything into `dev` that isn't ready for release.  We should be testing branches/PRs before merging into dev anyway.

Perhaps `dev` is now a misnomer, and the branch should be instead `release-candidate` or `rc` ?

**Comment by ecotechie** [comment]
Not the usual way a hotfix is released/handled. We decided to not use release branches a while back. Happy to change our process.

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Pull request merged**
