### PR TITLE
Add constant to deactivate check for production site.

### PR DESCRIPTION
**Pull request by ecotechie**
Easy way to bypass checking if we are in a production site or not.

### CODE REVIEW

**Comment by ecotechie** [comment]
Change this code to use a constant NERDPRESS_PRODUCTION_CHECK_BYPASS.

**Comment by ecotechie** [comment]
@blogtutor updated and ready to merge.

**Comment by blogtutor** [comment]
Looks good, except I"m confused on the "true" vs. "TRUE" capitalization.  You set this one to lower case, but the other returns for both FALSE and TRUE are all caps.  Should we clean that up, at least in this one function, to be consistent?

**Comment by ecotechie** [comment]
Once the Lint pull request is merged, they all will be :wink:

**Pull request merged**
