### PR TITLE
Gray out Cloudflare options if site is not on CFE #183

### PR DESCRIPTION
**Pull request by CNoemi94**
Disable/enable Cloudflare options based on the Firewall settings with JS.

### CODE REVIEW

**Comment by ecotechie** [comment]
@CNoemi94 Looks like this code may have broken the HelpScout widget. I no-longer see it in our menu or bottom right corner.

**Comment by blogtutor** [comment]
Just tested.  A quirk of this is that if there's a Cloudflare Token set, and then the setting changes to Sucuri or None, and then the settings are saved, the Cloudflare Token will be cleared.

That might not be a bad idea (effectively, automatically removing the Token from the options/database) -- but it also means if we're troubleshooting and need to go back to the Cloudflare setting we'll need to go find it again and add it back in. Let's discuss.

**Comment by CNoemi94** [comment]
Instead of disabling the field. I set the pointer-event to none, so in effect, disabling it with CSS but keeping the data after "Saving"

**Comment by ecotechie** [comment]
Thanks @CNoemi94! The widget is all good now. But it does clear the API Token still.

**Comment by ecotechie** [comment]
Looking good now! Thanks.

**Pull request merged**
