### PR TITLE
Added Perfmatters Delay JS Exclusion

### PR DESCRIPTION
**Pull request by CNoemi94**
Added the exclusion by default if Perfmatters is active on the site.

### CODE REVIEW

**Comment by blogtutor** [comment]
Thanks Crystal!  I just looked at the code and am wondering why there are WP Rocket references here.  Shouldn't this be only Perfmatters?

image

**Comment by blogtutor** [comment]
Just tested on dev.nerdpress.net.  I added a list of <script> tags to the <head>, one for each of the exclusions.

Here's what it looks like with Perfmatters delaying JS -- and our exclusions disabled --all good there:

image

Here's what it looks like with our exclusions enabled. None of these should be delayed:

image

I think it's the backslashes that are the issue... WP Rocket requires those for escaping, but Perfmatters seems to treat them literally.

image

Perhaps we should maintain a separate list of exclusions for Perfmatters in the `class-support-overrides.php` file?

**Comment by blogtutor** [comment]
Tested the branch on dev.nerdpress.net. Works great now! 

The perfmatters list was missing the `adt_ei` exclusion so I added that in. I also added "WP Recipe Maker" back in to the list displayed on the WP Rocket page.

Ideally, we should add a similar message to the Perfmatters settings page.  We could probably target  just above `#assets-delay_js_exclusions` ?

image

If we can get that in quickly Wednesday morning, let's go for it?  :)

**Comment by CNoemi94** [comment]
@blogtutor Added! 
image

**Comment by blogtutor** [comment]
@CNoemi94 Tested, looks great!

BUT I just realized that if we disable these exclusion lists in our plugin's settings, we shouldn't display that message. 🤦‍♂️  It's still displaying on both Rocket & Perfmatters even when they're disabled.

Could you please add some logic to hide those messages in those respective cases?

**Comment by blogtutor** [comment]
tested! looks good! merging!!!

**Pull request merged**
