### PR TITLE
2.3.2 Release

### PR DESCRIPTION
**Pull request by blogtutor**
Add JS delay exclusions for gpt.js

### CODE REVIEW

**Comment by blogtutor** [comment]
@CNoemi94 can you please review? super simple I just want a new pair of eyes on this.

**Review by CNoemi94 — APPROVED** [review]
Looks good! 👍

**Comment by blogtutor** [comment]
image

**Comment by blogtutor** [comment]
Crystal tested and confirmed good. 

https://nerd-press.slack.com/archives/C7N19NT6X/p1716397597864859

**Pull request merged**
